Add sample grafana dashboard for prometheus monitoring
SoftwareAG/terracotta-samples pull request #29
Opened 2022-08-05 13:34 UTC by guptakshit

2022-08-08 19:32 UTC, GaryWKeim approved these changes

2022-08-17 14:16 UTC, chrisdennis requested changes
The other samples are numbered... should this one be as well?

2022-08-17 14:16 UTC, chrisdennis commented on prometheus-grafana-integration/README.md
> +Contains a sample grafana dashboard for Terracotta metrics exposed in Prometheus format.
Should this README reference/include the images? If not, what are the images for in this context?

2022-08-17 14:16 UTC, chrisdennis commented on prometheus-grafana-integration/dashboard/dashboard.json
> +{
Is this file supposed to be human readable, or is it expected that a user uses tooling to edit it? If the former then it seems we should probably be reordering the keys. Right now they're alphabetical, which isn't really great for readability.

2022-08-19 13:24 UTC, guptakshit commented on prometheus-grafana-integration/dashboard/dashboard.json
> +{
No, this isn't supposed to be human readable. We can create dashboards in grafana web app, the UI provides an option to export it in a JSON format.
Users can import the dashboard by either uploading this JSON file or by providing the dashboard ID(if the dashboard is uploaded to grafana.com like https://grafana.com/grafana/dashboards/1860-node-exporter-full/)

Although users can edit this file, but it is expected to be done through grafana web app.

2022-08-22 14:07 UTC, guptakshit commented
In the above commit numbered the folder and updated README.md file

2022-08-22 14:10 UTC, guptakshit commented on 07-prometheus-grafana-integration/README.md
> +   <img src="./images/server-metrics-row.png" width="80%" alt="server-metrics-row">
used HTML instead of markdown syntax as it doesn't seem to support resizing of images. (Default 100% image size was appearing very large)

2022-08-22 14:48 UTC, chrisdennis approved these changes

2022-08-22 14:48 UTC, merged